services:
  # catalog:
  #   container_name: catalog-api
  #   build:
  #       dockerfile: ../src/Services/Catalog/Ecommerce.Catalog.Api/DockerFile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - "5432:5432"
    restart: always
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      command: --default-authentication-plugin=mysql_native_password
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"