services:
  catalog:
    build:
        dockerfile: ../src/Services/Catalog/Ecommerce.Catalog.Api/DockerFile
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - "5432:5432"
    restart: always
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql