FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Ecommerce.Catalog.Api/Ecommerce.Catalog.Api.csproj", "Ecommerce.Catalog.Api/"]
RUN dotnet restore "Ecommerce.Catalog.Api/Ecommerce.Catalog.Api.csproj"
COPY . .
WORKDIR "/src/Ecommerce.Catalog.Api"
RUN dotnet build "Ecommerce.Catalog.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ecommerce.Catalog.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Ecommerce.Catalog.Api.dll"]